version: '3.8'

services:
    db:
        image: mariadb:10.3
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:5.5.1-php7.2-fpm
        volumes:
            - web_data:/var/www/html
        restart: always
        expose:
            - 9000
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

    web:
        depends_on:
            - wordpress
        image: nginx:custom
        build: nginx
        volumes:
            - web_data:/var/www/html
        restart: always
        ports:
         - "8080:80"

volumes:
    db_data: {}
    web_data: {}